FROM python:3.8

COPY requirements.txt requirements.txt
RUN pip install -U pip \
    && pip install --no-cache-dir --upgrade setuptools wheel \
    && pip install -r requirements.txt \
    && rm requirements.txt

COPY ./app.py /app/app.py
COPY ./run.sh /app/run.sh
WORKDIR /app

ARG STAGE
ARG TENANT
ARG REDSHIFT_USERNAME
ARG REDSHIFT_PASSWORD
ARG REDSHIFT_HOST
ARG REDSHIFT_PORT
ARG REDSHIFT_IAM_ROLE
ARG DATA_LAKE
ARG DATA_LAKE_TYPE
ARG DATA_LAKE_ROOT_PATH
ARG DATA_LAKE_REGION
ARG MLFLOW_TRACKING_URI
ARG MLFLOW_TRACKING_TOKEN
ARG DATA_WAREHOUSE_TYPE
ENV STAGE=$STAGE\
    TENANT=$TENANT\
    API_KEY=$API_KEY \
    REDSHIFT_USERNAME=$REDSHIFT_USERNAME \
    REDSHIFT_PASSWORD=$REDSHIFT_PASSWORD \
    REDSHIFT_HOST=$REDSHIFT_HOST \
    REDSHIFT_PORT=$REDSHIFT_PORT \
    REDSHIFT_IAM_ROLE=$REDSHIFT_IAM_ROLE \
    DATA_LAKE=$DATA_LAKE \
    DATA_LAKE_TYPE=$DATA_LAKE_TYPE \
    DATA_LAKE_ROOT_PATH=$DATA_LAKE_ROOT_PATH \
    DATA_LAKE_REGION=$DATA_LAKE_REGION \
    DATA_WAREHOUSE_TYPE=$DATA_WAREHOUSE_TYPE

EXPOSE 8080

ENTRYPOINT ["bash", "run.sh"]